#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Input\ArrayInput;
use Symfony\Component\Console\Output\ConsoleOutput;
use Yuxiaobo\DockerPhpEnvironment\commands\InitCommand;
use Yuxiaobo\DockerPhpEnvironment\commands\WelcomeCommand;

require 'vendor/autoload.php';



$application = new Application();

$application->setName('Docker PHP Environment');
$application->setVersion('0.0.1');

$application->add(new InitCommand());
$application->add(new WelcomeCommand());

$input = new ArgvInput();
$output = new ConsoleOutput();

$application->run($input, $output);
