#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;
use Edk24\DockerPhpEnvironment\commands\InitCommand;
use Edk24\DockerPhpEnvironment\commands\WelcomeCommand;

require 'vendor/autoload.php';

define('ROOT_PATH', __DIR__);                   // 根目录
define('APP_PATH', getcwd());                   // 应用目录 (执行脚本所在目录)

$application = new Application();

$application->setName('Docker PHP Environment');
$application->setVersion('0.0.1');

$application->add(new InitCommand());
$application->add(new WelcomeCommand());

$input = new ArgvInput();
$output = new ConsoleOutput();

$application->run($input, $output);
